In [2]:
import pandas as pd
import numpy as np
np.random.seed(1)
import matplotlib.pyplot as plt
import pandas_profiling
from numpy import nan as NA

In [2]:
training = pd.read_csv('ALS_TrainingData_2223.csv')
testing = pd.read_csv('ALS_TestingData_78.csv')

In [4]:
training.head()

,ID,Age_mean,Albumin_max,Albumin_median,Albumin_min,Albumin_range,ALSFRS_slope,ALSFRS_Total_max,ALSFRS_Total_median,ALSFRS_Total_min,...,Sodium_min,Sodium_range,SubjectID,trunk_max,trunk_median,trunk_min,trunk_range,Urine.Ph_max,Urine.Ph_median,Urine.Ph_min
0,1,65,57.0,40.5,38.0,0.066202,-0.965608,30,28.0,22,...,143.0,0.017422,533,8,7.0,7,0.002646,6.0,6.0,6.0
1,2,48,45.0,41.0,39.0,0.010453,-0.921717,37,33.0,21,...,136.0,0.010453,649,8,7.0,5,0.005386,7.0,5.0,5.0
2,3,38,50.0,47.0,45.0,0.008929,-0.914787,24,14.0,10,...,140.0,0.008929,1234,5,0.0,0,0.008929,6.0,5.0,5.0
3,4,63,47.0,44.0,41.0,0.012111,-0.598361,30,29.0,24,...,138.0,0.012469,2492,5,5.0,3,0.004988,7.0,6.0,5.0
4,5,63,47.0,45.5,42.0,0.008292,-0.444039,32,27.5,20,...,138.0,0.008292,2956,6,4.0,1,0.008489,6.0,5.0,5.0

In [5]:
training.describe()

,ID,Age_mean,Albumin_max,Albumin_median,Albumin_min,Albumin_range,ALSFRS_slope,ALSFRS_Total_max,ALSFRS_Total_median,ALSFRS_Total_min,...,Sodium_min,Sodium_range,SubjectID,trunk_max,trunk_median,trunk_min,trunk_range,Urine.Ph_max,Urine.Ph_median,Urine.Ph_min
count,2223.000000,2223.000000,2223.000000,2223.000000,2223.000000,2223.000000,2223.000000,2223.000000,2223.000000,2223.000000,...,2223.000000,2223.000000,2223.000000,2223.000000,2223.000000,2223.000000,2223.000000,2223.000000,2223.000000,2223.000000
mean,1214.874944,54.550157,47.011134,43.952542,40.766347,0.013779,-0.728274,31.692308,27.104926,19.877193,...,136.755061,0.015000,498880.290148,6.203779,4.893387,2.955915,0.007136,6.820450,5.710639,5.183221
std,696.678300,11.396546,3.233980,2.654804,3.193087,0.009567,0.622329,5.314228,6.633643,8.583509,...,2.715247,0.009283,289923.528450,1.747660,2.146076,2.358095,0.004503,0.932141,0.625039,0.437222
min,1.000000,18.000000,37.000000,34.500000,24.000000,0.000000,-4.345238,11.000000,2.500000,0.000000,...,112.000000,0.000000,533.000000,0.000000,0.000000,0.000000,0.000000,5.000000,5.000000,5.000000
25%,614.500000,47.000000,45.000000,42.000000,39.000000,0.009042,-1.086310,29.000000,23.000000,14.000000,...,135.000000,0.010582,240825.500000,5.000000,3.000000,1.000000,0.003643,6.000000,5.000000,5.000000
50%,1213.000000,55.000000,47.000000,44.000000,41.000000,0.012111,-0.620748,33.000000,28.000000,20.000000,...,137.000000,0.013123,496835.000000,7.000000,5.000000,3.000000,0.006920,7.000000,6.000000,5.000000
75%,1815.500000,63.000000,49.000000,46.000000,43.000000,0.015873,-0.283832,36.000000,32.000000,27.000000,...,138.000000,0.017278,750300.500000,8.000000,6.500000,5.000000,0.009639,7.000000,6.000000,5.000000
max,2424.000000,81.000000,70.300000,51.100000,49.000000,0.243902,1.207011,40.000000,40.000000,40.000000,...,145.000000,0.142857,999482.000000,8.000000,8.000000,8.000000,0.042017,9.000000,9.000000,8.000000

In [6]:
testing.head()

,ID,Age_mean,Albumin_max,Albumin_median,Albumin_min,Albumin_range,ALSFRS_slope,ALSFRS_Total_max,ALSFRS_Total_median,ALSFRS_Total_min,...,trunk_min,trunk_range,Urine.Ph_max,Urine.Ph_median,Urine.Ph_min,Urine.Ph_range,White.Blood.Cell..WBC._max,White.Blood.Cell..WBC._median,White.Blood.Cell..WBC._min,White.Blood.Cell..WBC._range
0,3,65.906849,46.0,44.0,43,0.024590,-1.767329,33,5.0,2,...,0,0.006440,6.5,6.00,6.0,0.004098,8.57,7.680,6.60,0.016148
1,4,54.000000,39.0,36.0,33,0.013100,-1.351852,32,23.0,14,...,0,0.013100,6.5,5.50,5.0,0.003275,8.04,6.620,4.97,0.006703
2,5,56.394521,46.0,43.0,39,0.009736,-0.412429,15,10.0,2,...,0,0.000000,7.5,6.75,6.0,0.003456,8.90,7.160,5.01,0.005410
3,6,72.619178,50.0,42.5,41,0.092784,-0.383403,34,24.0,21,...,5,0.007752,7.5,7.00,6.0,0.024194,12.38,7.905,4.96,0.076495
4,9,65.000000,45.0,42.0,36,0.021327,0.000000,37,37.0,37,...,7,0.000000,6.0,5.50,5.0,0.002370,11.53,9.290,7.94,0.008507

In [7]:
testing.describe()

,ID,Age_mean,Albumin_max,Albumin_median,Albumin_min,Albumin_range,ALSFRS_slope,ALSFRS_Total_max,ALSFRS_Total_median,ALSFRS_Total_min,...,trunk_min,trunk_range,Urine.Ph_max,Urine.Ph_median,Urine.Ph_min,Urine.Ph_range,White.Blood.Cell..WBC._max,White.Blood.Cell..WBC._median,White.Blood.Cell..WBC._min,White.Blood.Cell..WBC._range
count,78.000000,78.000000,78.000000,78.000000,78.000000,78.000000,78.000000,78.000000,78.000000,78.000000,...,78.000000,78.000000,78.000000,78.000000,78.000000,78.000000,78.000000,78.000000,78.000000,78.000000
mean,51.589744,56.025571,45.256410,42.173077,38.910256,0.016753,-0.825866,29.807692,21.544872,14.705128,...,1.871795,0.007133,7.076923,6.192308,5.564103,0.004544,9.341795,6.789103,5.286026,0.012203
std,28.468910,10.514606,3.056549,3.083341,3.977815,0.013419,0.649497,6.107389,8.995015,9.532050,...,2.211886,0.003980,0.674570,0.572536,0.458392,0.004776,2.939529,1.683264,1.513861,0.014724
min,3.000000,24.583562,38.000000,35.000000,25.000000,0.004138,-3.041667,13.000000,2.000000,0.000000,...,0.000000,0.000000,6.000000,5.500000,5.000000,0.000000,4.110000,3.240000,1.430000,0.003078
25%,27.250000,51.000000,43.000000,40.000000,36.250000,0.011006,-1.315287,26.000000,16.500000,8.000000,...,0.000000,0.004490,6.500000,5.812500,5.000000,0.002278,7.767500,5.878750,4.330000,0.005658
50%,51.500000,57.000000,45.500000,42.250000,39.000000,0.013761,-0.679723,31.000000,22.000000,14.000000,...,1.000000,0.006365,7.000000,6.000000,5.500000,0.003390,8.750000,6.720000,5.320000,0.008402
75%,74.750000,62.180822,47.000000,44.000000,41.000000,0.018015,-0.390660,34.000000,28.000000,21.000000,...,3.000000,0.009639,7.500000,6.500000,6.000000,0.004715,10.690000,7.730000,6.125000,0.012471
max,100.000000,77.000000,51.000000,49.000000,47.000000,0.092784,0.325893,40.000000,39.000000,37.000000,...,7.000000,0.019048,9.000000,7.500000,7.000000,0.034483,22.490000,11.795000,9.500000,0.092045

In [10]:
training_profile = training.profile_report(title='Training Profile Report 1')
training_profile.to_file(output_file='pandas_profiling_reports/Training_Profile_1.html')

In [11]:
testing_profile = testing.profile_report(title='Testing Profile Report 1')
testing_profile.to_file(output_file='pandas_profiling_reports/Testing_Profile_1.html')

In [13]:
training2 = pd.read_csv('training2.csv')

In [14]:
training_profile2 = training2.profile_report(title='Training Profile Report 2')
training_profile2.to_file(output_file='pandas_profiling_reports/Training_Profile_2.html')

In [12]:
training_scaled = pd.read_csv('training_scaled.csv')

In [6]:
training_scaled.describe()

,Age_mean,Albumin_max,Albumin_median,Albumin_min,Albumin_range,ALSFRS_slope,ALSFRS_Total_max,ALSFRS_Total_median,ALSFRS_Total_min,ALSFRS_Total_range,...,Sodium_median,Sodium_min,Sodium_range,trunk_max,trunk_median,trunk_min,trunk_range,Urine.Ph_max,Urine.Ph_median,Urine.Ph_min
count,2.223000e+03,2.223000e+03,2.223000e+03,2.223000e+03,2.223000e+03,2.223000e+03,2.223000e+03,2.223000e+03,2.223000e+03,2.223000e+03,...,2.223000e+03,2.223000e+03,2.223000e+03,2.223000e+03,2.223000e+03,2.223000e+03,2.223000e+03,2.223000e+03,2.223000e+03,2.223000e+03
mean,5.162063e-16,-7.735103e-16,-1.414373e-16,2.844728e-16,7.671177e-17,3.835588e-17,-9.748787e-17,-3.579882e-16,-2.237427e-17,-4.474853e-17,...,6.019476e-15,-4.685810e-15,-8.989660e-17,-1.232183e-15,3.352144e-16,-1.981721e-16,1.438346e-16,3.747689e-16,-1.155471e-15,-2.589022e-16
std,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,...,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
min,-3.207126e+00,-3.095608e+00,-3.560543e+00,-5.250827e+00,-1.440274e+00,-5.811977e+00,-3.893756e+00,-3.709112e+00,-2.315742e+00,-1.611508e+00,...,-6.785491e+00,-9.117057e+00,-1.615872e+00,-3.549763e+00,-2.280156e+00,-1.253518e+00,-1.584713e+00,-1.952976e+00,-1.136952e+00,-4.190570e-01
25%,-6.624952e-01,-6.218757e-01,-7.354749e-01,-5.531786e-01,-4.951748e-01,-5.753150e-01,-5.066226e-01,-6.188042e-01,-6.847075e-01,-7.427795e-01,...,-6.398476e-01,-6.463724e-01,-4.759009e-01,-6.887946e-01,-8.822557e-01,-8.294473e-01,-7.756723e-01,-8.801775e-01,-1.136952e+00,-4.190570e-01
50%,3.947183e-02,-3.442694e-03,1.787642e-02,7.317456e-02,-1.743216e-01,1.727796e-01,2.460738e-01,1.349295e-01,1.430732e-02,-1.694654e-01,...,-8.115275e-02,9.020884e-02,-2.021283e-01,4.555928e-01,4.967797e-02,1.869499e-02,-4.781541e-02,1.926212e-01,4.629494e-01,-4.190570e-01
75%,7.414389e-01,6.149903e-01,7.712278e-01,6.995277e-01,2.189002e-01,7.141590e-01,8.105961e-01,7.379165e-01,8.298246e-01,5.424136e-01,...,4.775421e-01,4.584995e-01,2.453916e-01,1.027787e+00,7.486282e-01,8.668373e-01,5.558461e-01,1.926212e-01,4.629494e-01,-4.190570e-01
max,2.320865e+00,7.201302e+00,2.692274e+00,2.578587e+00,2.405435e+01,3.109744e+00,1.563292e+00,1.943890e+00,2.344357e+00,5.670481e+00,...,3.550364e+00,3.036534e+00,1.377374e+01,1.027787e+00,1.447578e+00,2.139051e+00,7.746452e+00,2.338218e+00,5.262653e+00,6.442448e+00

In [13]:
training_scaled_profile = training_scaled.profile_report(title='Training Scaled Profile Report')
training_scaled_profile.to_file(output_file='pandas_profiling_reports/Training_Scaled_Profile.html')